services:
  migration:
      build: .
      command: [ "alembic", "upgrade", "head" ]
      container_name: twin-calling-info-migration
      environment:
        database: $database
        database_schema: $database_schema

  http:
    build: .
    depends_on:
      - migration
    command: ["python", "-m", "twin_calling_info"]
    expose:
      - "8000"
    volumes:
      - ./twin_calling_info:/usr/src/twin_calling_info
    environment:
      database: $database
      database_schema: $database_schema
      debug_enabled: $debug_enabled
      interface_opened: $interface_opened
      twin_auth_url: $twin_auth_url
      twin_contacts_url: $twin_contacts_url
      twin_create_call_url: $twin_create_call_url
      twin_send_contacts_url: $twin_send_contacts_url
      twin_login: $twin_login
      twin_password: $twin_password
      twin_ttl: $twin_ttl
      twin_webhook: $twin_webhook
      tg_token: $tg_token
      tg_chat_id: $tg_chat_id
      redis_host: $redis_host
      redis_user: $redis_user
      redis_user_password: $redis_user_password
      redis_port: $redis_port
      redis_db: $redis_db
      TZ: Europe/Moscow
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_reverse-proxy"
      - "traefik.http.middlewares.twin_calling_info-prefix.stripprefix.prefixes=$https_prefix"
      - "traefik.http.middlewares.twin_calling_info-prefix.stripprefix.forceSlash=false"
      - "traefik.http.routers.twin_calling_info.tls=true"
      - "traefik.http.routers.twin_calling_info.rule=Host(`$host`) && PathPrefix(`$https_prefix`)"
      - "traefik.http.routers.twin_calling_info.middlewares=twin_calling_info-prefix"
    networks:
      - traefik_reverse-proxy
    restart: always

networks:
  traefik_reverse-proxy:
    external: true